#!/usr/bin/env -S guix shell guix blue guile emacs-no-x stow curl -- sh -c 'exec guile -e main -s "$(command -v blue)" "$@"' sh -f
;; -*- mode: scheme -*-
;; SPDX-FileCopyrightText: 2026 Nikita Mitasov <me@ch4og.com>
;; SPDX-License-Identifier: GPL-3.0-or-later
!#

(use-modules
 (blue types blueprint)
 (blue types command)
 (ice-9 match)
 (ice-9 ftw))

(define config-root
  (dirname (canonicalize-path (current-filename))))

(add-to-load-path config-root)

(define emacs-options
  "(setq enable-local-eval t enable-local-variables :all)")

(define emacs-format-expression
  "(progn (scheme-mode) (hack-local-variables) (indent-region (point-min) (point-max)) (save-buffer))")

(define (emacs-format-command file)
  (string-join `("emacs" "--batch" "--quick"
                 "--eval" ,(string-append "'" emacs-options "'")
                 ,file
                 "--eval" ,(string-append "'" emacs-format-expression "'")) " "))

(define-command (style-command args)
  ((invoke "style")
   (category 'shika)
   (synopsis "Format Scheme files")
   (help "Format all .scm files and blue with Emacs"))
  (let ((format-command (emacs-format-command "{}")))
    (system (string-join `("find"
                           ,(string-append config-root "/shika")
                           ,(string-append config-root "/etc")
                           "-type f"
                           "-name '*.scm'"
                           "-exec" ,format-command "\\;") " "))
    (system (emacs-format-command (string-append config-root "/blue")))))

(define-command (update-command args)
  ((invoke "up")
   (category 'shika)
   (synopsis "Update packages")
   (help "Update packages versions"))
  (for-each (lambda (name)
              (format #t "Refreshing ~a~%" name)
              (system (string-join `("guix refresh" "-L"
                                     ,config-root "-u"
                                     ,(string-append "--select='module:(shika packages " name ")'"))
                                   " ")))
            (map (lambda (f)
                   (substring f 0
                              (- (string-length f) 4)))
                 (filter (lambda (f)
                           (string-suffix? ".scm" f))
                         (scandir (string-append config-root "/shika/packages"))))))

(blueprint
 (commands (list style-command
                 update-command)))
