;;; SPDX-FileCopyrightText: 2025 Nikita Mitasov <me@ch4og.com>
;;; SPDX-License-Identifier: GPL-3.0-or-later

(define-module (shika home packages))
(use-modules (guix utils)
             (gnu packages)
             (gnu packages dns)
             (guix transformations)
             (nongnu packages nvidia))

(define-public %shika-home-packages
  (specifications->packages
   '("arashi-icon-theme"
     "bat"
     "bibata-cursor-theme"
     "bind:utils"
     "blueman"
     "bluez"
     "btop"
     "cliphist"
     "curl"
     "direnv"
     "dmenu-bluetooth"
     "dust"
     "emacs-no-x"
     "eog"
     "eza"
     "fastfetch"
     "fd"
     "file"
     "file-roller"
     "filezilla"
     "firefox"
     "flatpak"
     "font-awesome-nonfree"
     "fontforge"
     "font-google-noto"
     "font-google-noto-emoji"
     "font-google-noto-sans-cjk"
     "font-microsoft-web-core-fonts"
     "fzf"
     "ghostty"
     "gimp"
     "gnome-themes-extra"
     "gnupg"
     "grim"
     "grimblast"
     "heroic-nvidia"
     "honkers-railway-launcher-nvidia"
     "hyprpicker"
     "imagemagick"
     "jq"
     "jujutsu"
     "kdenlive"
     "lazygit"
     "libreoffice"
     "mangohud"
     "mangowc"
     "mpv-nvidia"
     "murrine"
     "ncurses"
     "networkmanager-dmenu"
     "nftables"
     "obs-nvidia"
     "obs-wlrobs"
     "pavucontrol"
     "pcmanfm"
     "pinentry"
     "pipewire"
     "playerctl"
     "protonup"
     "qbittorrent-enhanced"
     "quickshell@git"
     "remmina"
     "reuse"
     "ripgrep"
     "rofi"
     "slurp"
     "starship"
     "steam-nvidia"
     "swappy"
     "swaybg"
     "swaylock-effects"
     "swaynotificationcenter"
     "swww"
     "tmux"
     "tokyonight-gtk-theme"
     "torbrowser"
     "unzip"
     "uxplay"
     "virt-manager"
     "waybar-experimental"
     "wireplumber"
     "wl-clipboard"
     "wl-mirror"
     "wlr-dpms"
     "wtype"
     ;"xdg-desktop-portal"
     "xdg-desktop-portal-gtk"
     "xdg-desktop-portal-wlr@0.8.1"
     "xdg-utils"
     "zapret"
     "zip"
     "zoxide")))
