#!/usr/bin/env -S guix shell guile -- guile --no-auto-compile
!#
;; SPDX-FileCopyrightText: 2025 Nikita Mitasov <me@ch4og.com>
;; SPDX-License-Identifier: GPL-3.0-or-later
;; vim: filetype=scheme

(define repo-root
  (dirname (dirname (canonicalize-path (current-filename)))))

(add-to-load-path repo-root)

(use-modules (ice-9 match)
             (shika lib channels)
             (shika lib substitutes))

(define (run-guix kind extra-args)
  (let ((sudo (if (string=? kind "system") "sudo" "")))
    (display (string-append "Running " kind " reconfigure...\n"))
    (system (string-join (append (list "cd"
				       repo-root
				       "&&"
				       "exec"
                                       sudo
                                       "guix"
                                       "time-machine"
                                       "-C"
                                       (string-append repo-root "/shika/lib/channels.scm")
                                       "--"
                                       kind
                                       "reconfigure"
                                       (string-append repo-root "/shika/" kind "/config.scm")
                                       shika-subs-urls
                                       "-L"
				       repo-root) extra-args) " "))))

(define (usage command)
  (display (string-append "Usage: " command " COMMAND [args...]\n\n"))
  (display "Commands:\n")
  (display "  system   [args...]  - reconfigure system\n")
  (display "  home     [args...]  - reconfigure home\n"))

(define (selection cmd)
  (match (cdr cmd)
    (("system" . rest) (run-guix "system" rest))
    (("home" . rest) (run-guix "home" rest))
    (_ (usage (car cmd)) (exit 1))))

(selection (command-line))
